version: '2.3'

services:
  rosbag:
    image: gui
    volumes:
      - "${HOME}/vio/data:/root/data"
    network_mode: host
    command: /bin/bash -c "sleep 3; rosbag play /root/data/MH_01_easy.bag"

  rovio:
    image: rovio
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    command: /bin/bash -c "source /root/catkin_ws/devel/setup.bash; bash"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - "PYTHONUNBUFFERED=1"
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1

  rviz:
    image: gui
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - "PYTHONUNBUFFERED=1"
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
    depends_on:
      - vins-mono-event
    network_mode: host
    command: /bin/bash -c "source /root/catkin_ws/devel/setup.bash; sleep 5; roslaunch vins_estimator vins_rviz.launch"
    privileged: true
    runtime: nvidia
